name = "ThreadPinningCore"
uuid = "6f48bc29-05ce-4cc8-baad-4adcba581a18"
authors = ["Carsten Bauer <crstnbr@gmail.com> and contributors"]
version = "0.1"

[deps]
StableTasks = "91464d47-22a1-43fe-8b7f-2d57ee82463f"

[compat]
StableTasks = "0.1.5"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
