name = "ThreadPinningCore"
uuid = "6f48bc29-05ce-4cc8-baad-4adcba581a18"
authors = ["Carsten Bauer <crstnbr@gmail.com> and contributors"]
version = "0.4.2"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
StableTasks = "91464d47-22a1-43fe-8b7f-2d57ee82463f"

[compat]
PrecompileTools = "1.2"
StableTasks = "0.1.5"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
